### ISSUE TITLE
Stale devices cause weird behavior

### ISSUE THREAD

**Issue by sproctor** [ivanempire/lighthouse#7]
I didn't get to fully investigate this issue, but the device list gets corrupted when devices expire. I think [this](https://github.com/ivanempire/lighthouse/blob/main/lighthouse/src/main/java/com/ivanempire/lighthouse/core/RealLighthouseClient.kt#L29) is a mistake.

I think the `foundDevicesFlow` should be filtered to remove stale devices. Alternatively, the two flows could be `combine`d and lost devices filtered from the found devices (but that seems needlessly complicated). I'll suggest a change tomorrow if I have time.

It's possible that I'm misunderstanding exactly what is happening. In my example, I'm seeing the list fluctuate between two different lists after about 2 minutes.

**Comment by ivanempire** [comment]
`It's possible that I'm misunderstanding exactly what is happening. In my example, I'm seeing the list fluctuate between two different lists after about 2 minutes.`
Can you provide some logs? The operator may not be the correct one, but I do filter out devices every second if they haven't received a packet in a certain amount of time.

**Comment by sproctor** [comment]
```kotlin
flowOf(foundDevicesFlow, lostDevicesFlow)
            .flattenMerge()
```

That's the culprit. It emits a series of lists that can alternate between found devices and stale devices, not a combination of them in a single list. I committed a fix to my branch.

**Comment by sproctor** [comment]
The fact that empty lists are filtered is a workaround for the behavior of this bug when devices aren't expiring. When they do expire, instead of an empty list, you get a list with the expired device. I hope my branch https://github.com/sproctor/lighthouse/tree/time_refactor explains it well.

**Comment by ivanempire** [comment]
For visibility - this has been fixed locally for a bit now, I just haven't properly tested this/finished documentation. It's going out in the next release. 🚀

**Comment by sproctor** [comment]
To me, this logic still doesn't make sense. You're creating two flows from `backingDeviceList` then combining them. There's not really any point to combining them except you're making changes to state in a cold flow. I still recommend something like my changes here: https://github.com/sproctor/lighthouse/blob/f15cf6df54c1be45435db1f41bfeb503c945d267/lighthouse/src/main/java/com/ivanempire/lighthouse/core/RealDiscoveryManager.kt

**Comment by ivanempire** [comment]
Yeah I meant that this issue in general is something I've been working on - I ended up doing something really similar to your PR.

**Comment by sproctor** [comment]
I finally got around to upgrading and this issue is now fixed. I still prefer my method as it allows unit testing that the stale device removal works.
